### PR TITLE
Update Project.tsx

### PR DESCRIPTION
**Pull request by vedangit**
Added a hover class to <a>

### CODE REVIEW

**Review by murtazajoo — COMMENTED** [review]
Hey @vedangit! Great job on submitting your first pull request! 🎉 We appreciate your contribution and the effort you've put into improving our project. We'll review your changes and provide feedback promptly. Keep up the excellent work! If you have any questions or need further assistance, feel free to ask. We're here to support you! Once again, thank you for your valuable contribution. We look forward to collaborating with you on more pull requests in the future. Best regards, Murtaza Joo<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/murtazajooercontributing.md)</p>

**Comment by murtazajoo** [comment]
🔥 Awesome

**Comment by murtazajoo** [comment]
Tip: add the issue number in the pull request like #12.

It will automatically close the issue when the pull request is merged

**Comment by vedangit** [comment]
Thank you for the advice

**Pull request merged**
