### PR TITLE
feat: Add footer to website

### PR DESCRIPTION
**Pull request by akj2018**
Add a footer to the website with the following content 

open source is awesome 💜
OpenSourcer is an open-source project. Feel free to contribute and help us to make this project better
Copyright © 2023 by openSourcer. Under MIT License

Home_Page

Projects_Page

Docs_Page

### CODE REVIEW

**Review by murtazajoo — COMMENTED** [review]
Hey @akj2018! Great job on submitting your first pull request! 🎉 We appreciate your contribution and the effort you've put into improving our project. We'll review your changes and provide feedback promptly. Keep up the excellent work! If you have any questions or need further assistance, feel free to ask. We're here to support you! Once again, thank you for your valuable contribution. We look forward to collaborating with you on more pull requests in the future. Best regards, Murtaza Joo<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/murtazajooercontributing.md)</p>

**Comment by murtazajoo** [comment]
Great! 
But can you make it look like this 
image

- for font add class to footer "font-saira"

**Comment by akj2018** [comment]
Hi @murtazajoo, I have update the website with the template you shared and added new font "font-saira".
[Commit #[57f873b](https://github.com/murtazajoo/openSourcer/pull/16/commits/57f873b7e314163bf64cc9b03eb09489d5be1a0a)]

**Comment by murtazajoo** [comment]
Awesome 🚀

**Pull request merged**
